### ISSUE TITLE
Moving train_nces.py into examples 

### ISSUE THREAD

**Issue by Demirrr** [dice-group/Ontolearn#270]
This script should be located in the examples folder.
Would you @Jean-KOUAGOU or @alkidbaci please move this script into examples folder?

**Comment by Demirrr** [comment]
It wouldn't work if you haven't install ontolearn. See [this](https://stackoverflow.com/questions/714063/importing-modules-from-parent-folder) for a better understanding of no module found exception.

**Comment by Jean-KOUAGOU** [comment]
I can fix this. Let me try

**Comment by Demirrr** [comment]
Your date can be found at https://hobbitdata.informatik.uni-leipzig.de/NCES_Ontolearn_Data

Please remove or move all NCES sepecifiy data including .yml into examples

**Comment by alkidbaci** [comment]
I moved train_nces.py to examples but got some processes issues which were fixed by wrapping the argument parser code with ` if __name__ == '__main__':` and putting the rest of the code inside a method (e.g. `run`) to pass args. Another error was introduced during the "_SetTransformer starts training..._ " process which was something specific ending as follows:

>  File "C:\Users\alkid\PycharmProjects\Ontolearn\ontolearn\data_struct.py", line 165, in <listcomp>
>     labels = [self.vocab[atm] for atm in target]
> KeyError: 'âŠ”'

This is how it goes for me @Jean-KOUAGOU. I don't get the module absence problem

**Comment by Jean-KOUAGOU** [comment]
train_nces.py runs smoothly when executed outside the examples' folder
after executing ./big_gitext/download_nces_data

**Comment by Jean-KOUAGOU** [comment]
I mean with the new changes. Just run `python examples/train_nces.py`

**Comment by Demirrr** [comment]
Solved at https://github.com/dice-group/Ontolearn/pull/274
