### ISSUE TITLE
ConceptGenerator and Reasoner

### ISSUE THREAD

**Issue by Demirrr** [dice-group/Ontolearn#282]
To generate a concept in a description logic, a reasoner is not required.
`ConceptGenerator()` should not require a reasoner object at initialization.

Could you take care of this @alkidbaci ?

**Comment by alkidbaci** [comment]
`ConceptGenerator ` has many methods that uses the reasoner and these methods are used by other classes through a `KnowledgeBase `object because `KnowledgeBase `inherit from `ConceptGenerator`. If all you are saying is that a reasoner should not be required then I have to move these methods somewhere else, I'm thinking `KnowledgeBase` directly. If you have something else in mind I would like to hear.
