### ISSUE TITLE
Using Hobbit-Data to store pre-trained models and datasets

### ISSUE THREAD

**Issue by Demirrr** [dice-group/Ontolearn#288]
1. Create a directory => https://files.dice-research.org/projects/Ontolearn
2.  Create a knowledge base directory containing datasets, e.g. KGs/Family/family.owl
3. Zip (2) and upload into (1), e.g., https://files.dice-research.org/projects/Ontolearn/KGs.zip
4. Adjust github actions to download and unzip KGs.zip so that our tests can run as we have done in [the action of dice-embeddings](https://github.com/dice-group/dice-embeddings/blob/d46ef61175e82c0e5226efd5174757b044fce8c8/.github/workflows/github-actions-python-package.yml#L27)
5. Remove [big_gitext](https://github.com/dice-group/Ontolearn/tree/develop/big_gitext) repo
6. Remove KGs folder from the repo

In future, we can automize the process of downloading dataset as done in pytorch, e.g., `torchvision.datasets.CIFAR10(root='./data', download=True)` see [this](https://pytorch.org/vision/stable/generated/torchvision.datasets.CIFAR10.html) for more details.

Would you take care of this @alkidbaci if your workload allows ?
If something is not well explained or can be improved, please let me know :)

**Comment by alkidbaci** [comment]
@Jean-KOUAGOU Since `big_gitext` is removed now, the code for NCES external files need to be updated. Can you please take care of it? You can add the script https://github.com/dice-group/Ontolearn/blob/develop/big_gitext/download_nces_data again somewhere but I would suggest that you move the directory https://files.dice-research.org/projects/NCES under Ontolearn directory https://files.dice-research.org/projects/Ontolearn/  and make the changes in your script accordingly. Feel free to work in my branch [general_adjustments](https://github.com/dice-group/Ontolearn/tree/general_adjustments). After you make any change, please check the section _'Download external files'_ in `README.md ` and `docs/usage/02_installation.md` in case any information need to be added regarding your changes.

@Demirrr is there anything else I should add from the previous location https://files.dice-research.org/archive/GitExt/OntoPy/ ? It seems like the other files (some embeddings and pretrained agents used for Drill) are not really needed right now.

**Comment by Jean-KOUAGOU** [comment]
Ok. I will do that

**Comment by Jean-KOUAGOU** [comment]
@alkidbaci : The project NCES cannot be moved into Ontolearn as it contains data that is not only for Ontolearn. This should not be a problem I guess. In case this is really necessary, you might want to download https://files.dice-research.org/projects/NCES/NCES_Ontolearn_Data/NCESData.zip and add it into Ontolearn because that is the data for Ontolearn

**Comment by Jean-KOUAGOU** [comment]
Currently I use the following to download and extract the data into the required folder name:

wget https://files.dice-research.org/projects/NCES/NCES_Ontolearn_Data/NCESData.zip -O ./NCESData.zip
unzip -o ./NCESData.zip
rm -f ./NCESData.zip

**Comment by Jean-KOUAGOU** [comment]
I have updated the scripts taking into account that owlapy was moved into ontolearn. I also moved the download_nces_data script into examples and updated example notebooks accordingly.

**Comment by Jean-KOUAGOU** [comment]
If you add NCESData.zip into the Ontolearn I guess you will set up a general github action to automatically download all the data. In that case, please let me know

**Comment by alkidbaci** [comment]
Thanks for the update @Jean-KOUAGOU. 

> The project NCES cannot be moved into Ontolearn as it contains data that is not only for Ontolearn.

If that is the case, then we can leave the directories as they are. I'm not adding NCESData.zip again in Ontolearn directory because that would become redundant. Let's follow DRY principle and keep things simple.

**Comment by alkidbaci** [comment]
Just noticed there are some issues with the file download on `deploy_cl.py`. I will take care of them.
