### ISSUE TITLE
Refactoring: dice-group/ontolearn/owlapy into dice-group/owlapy

### ISSUE THREAD

**Issue by Demirrr** [dice-group/Ontolearn#309]
1. Create  dice-group/owlapy repo
2. Move dice-group/ontolearn/owlapy into (1).
3. Make the first release for owlapy https://pypi.org/project/owlapy (request the necesseary rights )
4. pip install owlapy==0.1.0
5. Refactor ontolearn to use owlapy

**Comment by alkidbaci** [comment]
The Owlapy module contains also the owlready2 directory where we have the base implementation for reasoners, ontology and ontology manager. Also there are the reasoners such a FIC and ComplexCEInstances. I think like these belong to Ontolearn instead of owlapy, because so far, we are promoting these as features of Ontolearn. I mentioned this earlier to Leonie. So should I leave the reasoners and the base implementation in Ontolearn and move the rest to owlapy repo? What do you think @Demirrr @LNSieger ?

**Comment by LNSieger** [comment]
I always wondered why these things are in the owlapy folder. There might be some more things that belong to Ontolearn. E.g. the class TopLevelCNF is in owlapy/util right now. Maybe in Ontolearn we can have a folder for concept learners, one for reasoning tools, and one for classifier+explainability, and we sort all things that aren't strictly owlapy into these?

**Comment by Demirrr** [comment]
Thank you for the explanations @alkidbaci and @LNSieger .

I agree with your stands, namely, reasoners should not be a part of owlapy. 

> Should I leave the reasoners and the base implementation in Ontolearn and move the rest to owlapy repo?

Yes, please.
