### ISSUE TITLE
Depricating ModelAdapter

### ISSUE THREAD

**Issue by Demirrr** [dice-group/Ontolearn#439]
I do not think that ModelAdapter is useful anymore.

1. https://ontolearn-docs-dice-group.netlify.app/autoapi/ontolearn/model_adapter/#ontolearn.model_adapter.ModelAdapter
2. https://ontolearn-docs-dice-group.netlify.app/autoapi/ontolearn/model_adapter/index.html#ontolearn.model_adapter.ModelAdapter
3. https://ontolearn-docs-dice-group.netlify.app/usage/03_examples.html#ex-4-using-model-adaptor

@sapkotaruz11 @alkidbaci shall we remove it in our next release ?

**Comment by alkidbaci** [comment]
Model adapter is supposed to ease the initialization of a model but as you do, I also think there is barely anyone finding this useful enough. I guess its okay to remove it. 

Should not remove the whole [model_adapter.py](https://github.com/dice-group/Ontolearn/blob/develop/ontolearn/model_adapter.py) module though because there are a few other useful methods/classes there. Maybe we can rename the module to something else or move the useful code to some other module.

**Comment by Demirrr** [comment]
Ideally, we should remove the script. As those useful methods/classes defined there are not related to model_adapter, e.g. Trainer.
Yet, for the time being, we can only focus on deleting the ModelAdapter class along with the related tests

**Comment by alkidbaci** [comment]
Should I take this on?

**Comment by Demirrr** [comment]
please do

**Comment by sapkotaruz11** [comment]
Maybe it would be nice to rename the script as well. The execute function in the model_adapter is directly called from the main.py, and once we remove the model_adapter function, the naming of the script might seem somewhat confusing.
